name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        db-type:
          - mysql
          - mysql80
          - pgsql
          - sqlite

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      memcached:
        image: memcached
        ports:
          - 11211:11211

    env:
      DB: ${{ matrix.db-type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Start MySQL 5.6
        if: matrix.db-type == 'mysql'
        run: |
          docker run -d --name mysql56 \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=cakephp_test \
            -p 3306:3306 \
            --health-cmd="mysqladmin ping" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            mysql:5.6

          # Wait for MySQL to be ready
          for i in {1..30}; do
            if docker exec mysql56 mysqladmin ping -h localhost -u root -proot &> /dev/null; then
              echo "MySQL 5.6 is ready"
              break
            fi
            echo "Waiting for MySQL 5.6..."
            sleep 2
          done

      - name: Start MySQL 8.0
        if: matrix.db-type == 'mysql80'
        run: |
          docker run -d --name mysql80 \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=cakephp_test \
            -p 3307:3306 \
            --health-cmd="mysqladmin ping" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=3 \
            mysql:8.0

          # Wait for MySQL 8.0 to be ready
          for i in {1..30}; do
            if docker exec mysql80 mysqladmin ping -h localhost -u root -proot &> /dev/null; then
              echo "MySQL 8.0 is ready"
              break
            fi
            echo "Waiting for MySQL 8.0..."
            sleep 2
          done

      - name: Start PostgreSQL 9.4
        if: matrix.db-type == 'pgsql'
        run: |
          docker run -d --name postgres94 \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=cakephp_test \
            -p 5432:5432 \
            --health-cmd="pg_isready" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=5 \
            postgres:9.4

          # Wait for PostgreSQL to be ready
          for i in {1..30}; do
            if docker exec postgres94 pg_isready -U postgres &> /dev/null; then
              echo "PostgreSQL 9.4 is ready"
              break
            fi
            echo "Waiting for PostgreSQL 9.4..."
            sleep 2
          done

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: apcu, memcache, memcached, redis, mcrypt, pdo_mysql, pdo_pgsql, pdo_sqlite
          ini-values: |
            apc.enable_cli=1
          coverage: xdebug

      - name: Enable Autoload
        run: echo "require_once dirname(__DIR__, 2) . DS . 'vendors/autoload.php';" >> app/Config/bootstrap.php

      - name: locale-gen
        run: |
          sudo locale-gen de_DE;
          sudo locale-gen es_ES;

      - name: Create Another Databases for MySQL
        if: matrix.db-type == 'mysql'
        run: |
          env MYSQL_PWD=root mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE cakephp_test2;';
          env MYSQL_PWD=root mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE cakephp_test3;';

      - name: Create Another Databases for MySQL 8.0
        if: matrix.db-type == 'mysql80'
        run: |
          env MYSQL_PWD=root mysql -h 127.0.0.1 -P 3307 -u root -e 'CREATE DATABASE cakephp_test2;';
          env MYSQL_PWD=root mysql -h 127.0.0.1 -P 3307 -u root -e 'CREATE DATABASE cakephp_test3;';

      - name: Create Another Databases for PostgreSQL
        if: matrix.db-type == 'pgsql'
        run: |
          env PGPASSWORD=postgres psql -c 'CREATE SCHEMA test2;' -h 127.0.0.1 -U postgres -d cakephp_test;
          env PGPASSWORD=postgres psql -c 'CREATE SCHEMA test3;' -h 127.0.0.1 -U postgres -d cakephp_test;

      - name: Make temporary directories writable
        run: chmod -R 777 ./app/tmp

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-composer-

      - name: Install Composer Packages
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy database.php
        run: cp ./lib/Cake/Test/Config/database.php ./app/Config/

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run Tests
        run: ./vendors/bin/phpunit --coverage-clover coverage.xml --log-junit junit.xml --colors=always

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          use_oidc: true
          file: ./junit.xml
          flags: php${{ matrix.php-version }}-${{ matrix.db-type }}
          name: PHP ${{ matrix.php-version }} - ${{ matrix.db-type }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          flags: php${{ matrix.php-version }}-${{ matrix.db-type }}
          name: PHP ${{ matrix.php-version }} - ${{ matrix.db-type }}

      - name: Stop MySQL 5.6
        if: always() && matrix.db-type == 'mysql'
        run: docker stop mysql56 && docker rm mysql56 || true

      - name: Stop MySQL 8.0
        if: always() && matrix.db-type == 'mysql80'
        run: docker stop mysql80 && docker rm mysql80 || true

      - name: Stop PostgreSQL 9.4
        if: always() && matrix.db-type == 'pgsql'
        run: docker stop postgres94 && docker rm postgres94 || true

  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Composer get cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php8.4-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php8.4-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run static type analysis
        run: ./vendors/bin/phpcs
